[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
voxelize = "0.8.88"
actix-web = "4.4.0"
specs = { version = "0.20.0", features = ["specs-derive", "serde"] }


# [target.x86_64-unknown-linux-gnu]
# linker = "x86_64-linux-musl-gcc"