name: CI

on:
    push:
        branches:
            - main

concurrency:
    group: ${{ github.ref }}
    cancel-in-progress: true

env:
    DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
    FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
    deps:
        timeout-minutes: 30
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  # fetch-depth: 0
                  submodules: recursive
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  registry-url: https://registry.npmjs.org/
            - uses: dopplerhq/cli-action@v2
            - uses: actions-rust-lang/setup-rust-toolchain@v1
            # setup pnpm
            - uses: pnpm/action-setup@v2
              with:
                  version: 9
                  run_install: false
            - name: Install pnpm dependencies (with cache)
              uses: covbot/pnpm-install-with-cache@v1
            - uses: superfly/flyctl-actions/setup-flyctl@master
              with:
                  version: 0.2.60
            - run: flyctl auth docker
            - run: pnpm run build:voxelize
            - name: Expose GitHub Runtime
              uses: crazy-max/ghaction-github-runtime@v2
            - run: pnpm run --no-bail --parallel --filter website --filter server deployment
